### ISSUE TITLE
issue with running test-client in 5GHz mode

### ISSUE THREAD

**Issue by neukatan** [vanhoefm/krackattacks-scripts#30] opened 2017-12-05 22:16 UTC
Has anyone able to run the test client in 5GHz mode? I changed the hw_mode=a and Channel =36 in hostapd.conf.

Also ensured that 5GHz supported in my computers, two different ones running Intel/AC 7265 (iwlwifi) and Killer 1535 / QCA6174 (ath10k_pci). I am testing on ubuntu 16.04 x86_64.

Both of them give the following error:
IEEE 802.11 Configured channel (36) not found from the channel list of current mode (2) IEEE 802.11a

I am trying to test a device which has 5GHz only radio and haven't had success with wifi allicance test tool or krackattacks-scripts on which alliance tool based on.

Any help or direction in this topic is appreciated. Hope i am not missing something simple in my configuration.

I am trying with various combinations in hostapd conf, but reaching no where so far. Will keep the thread posted if there are any updates ...

Here is the error i am running into:

`[17:23:15] Note: disable Wi-Fi in network manager & disable hardware encryption. Both may interfere with this script.
[17:23:15] Starting hostapd ...
Configuration file: /home/test/krackattacks-scripts/krackattack/hostapd.conf
wlp2s0: IEEE 802.11 Configured channel (36) not found from the channel list of current mode (2) IEEE 802.11a
wlp2s0: IEEE 802.11 Hardware does not support configured channel
Could not select hw_mode and channel. (-3)
wlp2s0: interface state UNINITIALIZED->DISABLED
wlp2s0: AP-DISABLED 
wlp2s0: Unable to setup interface.
wlp2s0: interface state DISABLED->DISABLED
wlp2s0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlp2s0 wasn't started
nl80211: deinit ifname=wlp2s0 disabled_11b_rates=0
connect exception  hostapd_ctrl/wlp2s0 9877
[17:23:16] It seems hostapd did not start properly, please inspect its output.
[17:23:16] Did you disable Wi-Fi in the network manager? Otherwise hostapd won't work.
Traceback (most recent call last):
  File "./krack-test-client.py", line 617, in <module>
    attack.run(test_grouphs=test_grouphs, test_tptk=test_tptk)
  File "./krack-test-client.py", line 488, in run
    self.hostapd_ctrl = Ctrl("hostapd_ctrl/" + self.nic_iface)
  File "/home/test/krackattacks-scripts/krackattack/wpaspy.py", line 49, in __init__
    socket.SOCK_DGRAM)
socket.gaierror: [Errno -3] Temporary failure in name resolution
[17:23:16] Closing hostapd and cleaning up ...
`

**Comment by vanhoefm** [comment] 2017-12-21 02:42
This issue is a duplicate of #10 

Perhaps due to regulatory settings you are now allowed to create an AP on a 5 GHz channel.

**Closed as completed by vanhoefm** 2017-12-21 02:42 UTC

**Comment by kalpittiwari** [comment] 2018-01-29 13:24
@akatragadda Did you find the fix for this?
